// ─────────────────────────────────────────────────────────
// Mock data — used when Supabase is not yet connected.
// Replace usages with real Supabase queries as you build.
// ─────────────────────────────────────────────────────────

import type { Profile, Availability, ChatRequest } from "@/types";

export const MOCK_PLEDGE: Profile = {
  id: "pledge-001",
  email: "jsutherland@bu.edu",
  full_name: "Jamie Sutherland",
  initials: "JS",
  role: "pledge",
  major: "Computer Science",
  grad_year: 2027,
  ktp_role: null,
  bio: null,
  avatar_color: "blue",
  available_this_week: true,
  budget_max: 15,
  locations: ["BU campus (Comm Ave)", "Kenmore / Fenway"],
  transport: ["Walking", "MBTA / T"],
  food_prefs: ["Coffee", "Casual dining"],
  sports: ["Basketball", "Football"],
  hobbies: ["Hackathons", "Gaming"],
  preferred_spots: [],
  profile_complete: true,
  created_at: "2025-01-10T00:00:00Z",
  updated_at: "2025-03-01T00:00:00Z",
};

export const MOCK_PLEDGE_AVAIL: Availability = {
  id: "avail-pledge-001",
  user_id: "pledge-001",
  time_blocks: ["0,2","0,3","0,4","1,2","1,3","2,5","2,6","3,2","3,3","4,1","4,2"],
  week_of: null,
  created_at: "2025-03-01T00:00:00Z",
  updated_at: "2025-03-01T00:00:00Z",
};

export const MOCK_BROTHERS: Profile[] = [
  {
    id: "brother-001", email: "akim@bu.edu",
    full_name: "Alex Kim", initials: "AK", role: "brother",
    major: "Computer Science", grad_year: 2026, ktp_role: "Treasurer",
    bio: "Junior in CS, interning at Fidelity this summer. Love talking fintech, career advice, and pickup basketball.",
    avatar_color: "blue", available_this_week: true,
    budget_max: 18,
    locations: ["BU campus (Comm Ave)", "Kenmore / Fenway", "Back Bay"],
    transport: ["Walking", "MBTA / T"],
    food_prefs: ["Coffee", "Casual dining"],
    sports: ["Basketball", "Football", "Baseball"],
    hobbies: ["Hackathons", "Gaming", "Startups"],
    preferred_spots: ["Pavement Coffeehouse (Comm Ave)", "Dunkin on Bay State Rd"],
    profile_complete: true,
    created_at: "2024-09-01T00:00:00Z", updated_at: "2025-03-10T00:00:00Z",
  },
  {
    id: "brother-002", email: "mlee@bu.edu",
    full_name: "Marcus Lee", initials: "ML", role: "brother",
    major: "ECE", grad_year: 2025, ktp_role: "VP",
    bio: "Senior ECE, president of BU IEEE. Happy to chat about grad school, research, or the ECE curriculum.",
    avatar_color: "green", available_this_week: true,
    budget_max: 20,
    locations: ["BU campus (Comm Ave)", "Kenmore / Fenway", "Allston / Brighton"],
    transport: ["Walking", "MBTA / T", "Bike"],
    food_prefs: ["Boba / Tea", "Casual dining"],
    sports: ["Soccer", "Basketball"],
    hobbies: ["Music", "Film", "Startups"],
    preferred_spots: ["Gong Cha (Comm Ave)", "George Sherman Union"],
    profile_complete: true,
    created_at: "2024-09-01T00:00:00Z", updated_at: "2025-03-12T00:00:00Z",
  },
  {
    id: "brother-003", email: "jpark@bu.edu",
    full_name: "Jordan Park", initials: "JP", role: "brother",
    major: "Data Science", grad_year: 2027, ktp_role: "Member",
    bio: "Sophomore DS, working on a sports analytics side project. Big Red Sox fan.",
    avatar_color: "blue", available_this_week: true,
    budget_max: 12,
    locations: ["BU campus (Comm Ave)", "Kenmore / Fenway"],
    transport: ["Walking"],
    food_prefs: ["Coffee", "Dining hall"],
    sports: ["Baseball", "Running"],
    hobbies: ["Design", "Reading", "Film"],
    preferred_spots: ["BU Dining Hall", "Starbucks on Comm Ave"],
    profile_complete: true,
    created_at: "2024-09-01T00:00:00Z", updated_at: "2025-03-08T00:00:00Z",
  },
  {
    id: "brother-004", email: "srusso@bu.edu",
    full_name: "Sam Russo", initials: "SR", role: "brother",
    major: "Mechanical Engineering", grad_year: 2026, ktp_role: "Member",
    bio: "Junior MechE, big NFL guy. Can talk engineering internships, Boston sports, or anything outdoors.",
    avatar_color: "blue", available_this_week: false,
    budget_max: 10,
    locations: ["Allston / Brighton", "BU campus (Comm Ave)"],
    transport: ["Walking", "MBTA / T"],
    food_prefs: ["Casual dining", "Brunch"],
    sports: ["Football", "Hockey"],
    hobbies: ["Fitness", "Gaming", "Travel"],
    preferred_spots: ["Sweetgreen (Comm Ave)", "Area Four"],
    profile_complete: true,
    created_at: "2024-09-01T00:00:00Z", updated_at: "2025-03-01T00:00:00Z",
  },
  {
    id: "brother-005", email: "tng@bu.edu",
    full_name: "Tyler Ng", initials: "TN", role: "brother",
    major: "Computer Science", grad_year: 2025, ktp_role: "President",
    bio: "Senior CS, co-founder of a BU startup. Love talking entrepreneurship, product, and life after college.",
    avatar_color: "green", available_this_week: true,
    budget_max: 25,
    locations: ["Back Bay", "Kenmore / Fenway", "Downtown / Financial"],
    transport: ["Walking", "MBTA / T"],
    food_prefs: ["Coffee", "Brunch"],
    sports: ["Tennis", "Running"],
    hobbies: ["Startups", "Reading", "Travel"],
    preferred_spots: ["The Thinking Cup", "Tatte Bakery"],
    profile_complete: true,
    created_at: "2024-09-01T00:00:00Z", updated_at: "2025-03-14T00:00:00Z",
  },
  {
    id: "brother-006", email: "owilliams@bu.edu",
    full_name: "Omar Williams", initials: "OW", role: "brother",
    major: "Computer Engineering", grad_year: 2026, ktp_role: "Member",
    bio: "Junior CE, heavily into embedded systems and robotics. Also a big FIFA player.",
    avatar_color: "blue", available_this_week: false,
    budget_max: 15,
    locations: ["BU campus (Comm Ave)", "Cambridge / MIT"],
    transport: ["MBTA / T", "Bike"],
    food_prefs: ["Coffee", "Boba / Tea"],
    sports: ["Basketball", "Soccer"],
    hobbies: ["Gaming", "Music", "Hackathons"],
    preferred_spots: ["Voltage Coffee (Cambridge)", "BU GSU"],
    profile_complete: true,
    created_at: "2024-09-01T00:00:00Z", updated_at: "2025-03-05T00:00:00Z",
  },
  {
    id: "brother-007", email: "psharma@bu.edu",
    full_name: "Priya Sharma", initials: "PS", role: "brother",
    major: "CS / Mathematics", grad_year: 2026, ktp_role: "Secretary",
    bio: "Junior CS+Math, interested in ML research. Ask me about undergrad research, women in tech, or Boston hidden gems.",
    avatar_color: "green", available_this_week: true,
    budget_max: 15,
    locations: ["BU campus (Comm Ave)", "Kenmore / Fenway", "South End"],
    transport: ["Walking", "MBTA / T"],
    food_prefs: ["Coffee", "Boba / Tea"],
    sports: ["Running", "Tennis"],
    hobbies: ["Design", "Hackathons", "Music"],
    preferred_spots: ["Ogawa Coffee", "Pavement BU"],
    profile_complete: true,
    created_at: "2024-09-01T00:00:00Z", updated_at: "2025-03-11T00:00:00Z",
  },
  {
    id: "brother-008", email: "ctanaka@bu.edu",
    full_name: "Chris Tanaka", initials: "CT", role: "brother",
    major: "Finance / CS", grad_year: 2027, ktp_role: "Member",
    bio: "Sophomore double major, interning at a trading firm. Love chatting finance, side projects, or just coffee.",
    avatar_color: "blue", available_this_week: true,
    budget_max: 20,
    locations: ["Kenmore / Fenway", "Back Bay", "Downtown / Financial"],
    transport: ["Walking", "MBTA / T"],
    food_prefs: ["Coffee", "Casual dining"],
    sports: ["Baseball", "Basketball"],
    hobbies: ["Startups", "Gaming", "Fitness"],
    preferred_spots: ["Flour Bakery", "Starbucks Boylston"],
    profile_complete: true,
    created_at: "2024-09-01T00:00:00Z", updated_at: "2025-03-13T00:00:00Z",
  },
];

export const MOCK_BROTHER_AVAILS: Map<string, Availability> = new Map([
  ["brother-001", { id:"a1", user_id:"brother-001", time_blocks:["0,2","0,3","0,4","1,2","1,3","1,4","2,5","2,6","3,2","3,3","4,1","4,2","4,3"], week_of:null, created_at:"", updated_at:"" }],
  ["brother-002", { id:"a2", user_id:"brother-002", time_blocks:["1,2","1,3","2,2","2,3","3,4","3,5","3,6"], week_of:null, created_at:"", updated_at:"" }],
  ["brother-003", { id:"a3", user_id:"brother-003", time_blocks:["0,4","0,5","1,4","2,2","4,1","4,2"], week_of:null, created_at:"", updated_at:"" }],
  ["brother-004", { id:"a4", user_id:"brother-004", time_blocks:["2,3","2,4","3,1","3,2","4,4","4,5"], week_of:null, created_at:"", updated_at:"" }],
  ["brother-005", { id:"a5", user_id:"brother-005", time_blocks:["0,1","0,2","1,5","1,6","3,2","3,3","4,3"], week_of:null, created_at:"", updated_at:"" }],
  ["brother-006", { id:"a6", user_id:"brother-006", time_blocks:["1,1","1,2","2,4","2,5","3,5","3,6"], week_of:null, created_at:"", updated_at:"" }],
  ["brother-007", { id:"a7", user_id:"brother-007", time_blocks:["0,2","0,3","1,2","2,3","2,4","4,1","4,2"], week_of:null, created_at:"", updated_at:"" }],
  ["brother-008", { id:"a8", user_id:"brother-008", time_blocks:["0,3","0,4","1,4","1,5","3,2","3,3","4,2"], week_of:null, created_at:"", updated_at:"" }],
]);

export const MOCK_CHATS: ChatRequest[] = [
  {
    id: "chat-001", pledge_id: "pledge-001", brother_id: "brother-001",
    status: "confirmed", proposed_time: "2025-03-25T15:00:00Z",
    confirmed_time: "2025-03-25T15:00:00Z", location: "Pavement Coffeehouse (Comm Ave)",
    pledge_note: "Looking forward to chatting about CS internships!",
    pledge_marked_complete: false, brother_marked_complete: false,
    created_at: "2025-03-18T10:00:00Z", updated_at: "2025-03-19T09:00:00Z",
    brother: { id:"brother-001", full_name:"Alex Kim", initials:"AK", avatar_color:"blue" } as Profile,
  },
  {
    id: "chat-002", pledge_id: "pledge-001", brother_id: "brother-002",
    status: "completed", proposed_time: "2025-03-11T16:00:00Z",
    confirmed_time: "2025-03-11T16:00:00Z", location: "George Sherman Union",
    pledge_note: null,
    pledge_marked_complete: true, brother_marked_complete: true,
    created_at: "2025-03-08T00:00:00Z", updated_at: "2025-03-11T18:00:00Z",
    brother: { id:"brother-002", full_name:"Marcus Lee", initials:"ML", avatar_color:"green" } as Profile,
  },
  {
    id: "chat-003", pledge_id: "pledge-001", brother_id: "brother-005",
    status: "completed", proposed_time: "2025-03-05T14:00:00Z",
    confirmed_time: "2025-03-05T14:00:00Z", location: "Starbucks Comm Ave",
    pledge_note: null,
    pledge_marked_complete: true, brother_marked_complete: true,
    created_at: "2025-03-01T00:00:00Z", updated_at: "2025-03-05T16:00:00Z",
    brother: { id:"brother-005", full_name:"Tyler Ng", initials:"TN", avatar_color:"green" } as Profile,
  },
];
